name: Website Deployment

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.79.0"

      - name: Build
        run: cd website/ && hugo --minify

      - name: Deploy website to the branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: website/public
          publish_branch: public
          user_name: hugo-profile bot
          user_email: githubactionsbot@users.noreply.github.com
